services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_encurtador
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encurtador
    volumes:
      - pgdata:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    container_name: valkey_encurtador
    ports:
      - "6379:6379"

volumes:
  pgdata:
